### ISSUE TITLE
Strange error in whm export.

### ISSUE THREAD

**Issue by mrStafflink** [amorgun/blender_dow#17]
Greetings, I have a strange error when exporting a berserk Khorn model. I created two more deaths for him, and after exporting it, I get this.... The strangest thing is that in the object editor there are no errors and animations work, maybe it is not dangerous and just a warning a?  

That's after exporting whm/sgm. 
![Скриншот 12-12-2024 213045](https://github.com/user-attachments/assets/a21311cd-9b83-4e5b-a3a5-518f4486b269)

It's okay in here. 
![Скриншот 12-12-2024 213452](https://github.com/user-attachments/assets/39faccd4-0f73-4f9a-9633-5468e79e89a4)

![Скриншот 12-12-2024 213509](https://github.com/user-attachments/assets/a28f3737-8c62-46fe-8917-32cbfbef3d0d)

**Comment by amorgun** [comment]
It should exported regardless but this warning means your results may differ from what you expect. `force_invisible` fcurves should have at most 1 keyframe because they are treated as a constant flag for an animation and mesh pair. Your model has several `force_invisible` values present for the mesh. My best guess is that it's a side-effect of copying keyframes from another animation.

**Comment by mrStafflink** [comment]
So it's dangerous? Or is not terrible, animations in the game and in OE work normally.

Yes, I took a few frames from other animations, exactly 0 frame copied. I just animations of getting, made it so that they fit and for normal death from shooting combat.

**Comment by mrStafflink** [comment]
I think this article can be closed, as I have checked all animations in berserk and no errors in the object editor and in the game itself, and when exploring importing this model and then exporting, there are no these errors and warnings. Everything works the way I intended it to work.
